name: Build C++ EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and compile C++
        shell: powershell
        run: |
          $cpp = Get-ChildItem -Path . -Filter *.cpp -Recurse | Select-Object -First 1

          if (-not $cpp) {
            Write-Error "File .cpp tidak ditemukan!"
            exit 1
          }

          Write-Host "File C++ ditemukan: $($cpp.FullName)"
          g++ "$($cpp.FullName)" -o program.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: program-exe
          path: program.exe
